Repository Rosen-Team-B/Rosen_B_2, pull requests merged in 2023-01, with the labels that each got.

#13 Adding BE from old repo to new repo
  rosen_backend/.dockerignore
  rosen_backend/.gitignore
  rosen_backend/Dockerfile
  rosen_backend/README.md
  rosen_backend/manage.py
  rosen_backend/requirements.txt
  rosen_backend/siteConfig/__init__.py
  rosen_backend/siteConfig/asgi.py
  rosen_backend/siteConfig/settings.py
  rosen_backend/siteConfig/urls.py
  rosen_backend/siteConfig/wsgi.py
  rosen_backend/videoUpload/__init__.py
  rosen_backend/videoUpload/admin.py
  rosen_backend/videoUpload/apps.py
  rosen_backend/videoUpload/migrations/__init__.py
  rosen_backend/videoUpload/models.py
  rosen_backend/videoUpload/serializers.py
  rosen_backend/videoUpload/tests.py
  rosen_backend/videoUpload/urls.py
  rosen_backend/videoUpload/views.py
Labels: task

#18 copy pasted from local file
  rosen_frontend/pages/selectableImage.tsx
Labels: task

#22 Readme update
  README.md
Labels: chore

#23 Image Upload Functionality
  rosen_backend/videoUpload/admin.py
  rosen_backend/videoUpload/models.py
  rosen_backend/videoUpload/serializers.py
Labels: exploration

#25 Backend Refactor
  rosen_backend/.gitignore
  rosen_backend/requirements.txt
  rosen_backend/siteConfig/settings.py
  rosen_backend/siteConfig/urls.py
  rosen_backend/videoUpload/admin.py
  rosen_backend/videoUpload/migrations/0001_initial.py
  rosen_backend/videoUpload/migrations/0002_videouploadmodel_delete_videoupload.py
  rosen_backend/videoUpload/migrations/0003_imagemodel_rename_videouploadmodel_videomodel.py
  rosen_backend/videoUpload/models.py
  rosen_backend/videoUpload/serializers.py
  rosen_backend/videoUpload/urls.py
  rosen_backend/videoUpload/views.py
Labels: chore

#36 Docker repo
  docker-compose.yaml
  rosen_frontend/.dockerignore
  rosen_frontend/Dockerfile
Labels: task

#37 Github Actions
  .github/workflows/docker-image.yml
Labels: chore

#43 fixed it
  rosen_frontend/pages/selectableImage.tsx
  rosen_frontend/pages/selectableImageGallery.tsx
Labels: task

#42 Split Video into individual frames
  rosen_backend/videoUpload/apps.py
  rosen_backend/videoUpload/signals.py
Labels: exploration

#47 Documentation carry over
  documentation/design ideas w9.md
  documentation/meetings/clientMeetings/2022 09 27 - Client meeting W3  part 1.md
  documentation/meetings/clientMeetings/2022 10 06 - Client meeting W4
  documentation/meetings/clientMeetings/2022 10 11 - Client Meeting W5
  documentation/meetings/clientMeetings/2022 10 20 - Client Meeting W7
  documentation/meetings/clientMeetings/2022 10 25 - Client Meeting W8
  documentation/meetings/clientMeetings/2022 11 01 - Client Meeting W9
  documentation/meetings/clientMeetings/2022 11 15 - Client Meeting W11
  documentation/meetings/clientMeetings/2022 11 29 - Client Meeting W13.md
  documentation/meetings/teamMeetings/2022 09 29 - Team meeting W3.md
  documentation/requirements-engineering/storyboarding/README.MD
  documentation/requirements-engineering/storyboarding/img_1.jpg
  documentation/requirements-engineering/storyboarding/img_2.jpg
  documentation/requirements-engineering/use-case/README.MD
  documentation/requirements-engineering/use-case/img_1.jpg
  documentation/specifications/README.MD
  documentation/specifications/requirements report.md
Labels: chore
